// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
 
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
 
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWyQRfadVZG07tXOK5eAnnbiJDwUVHtlI',
    appId: '1:53591657125:web:9e7e3d1eef2b12548b5b4c',
    messagingSenderId: '53591657125',
    projectId: 'appchat-c68c1',
    authDomain: 'appchat-c68c1.firebaseapp.com',
    storageBucket: 'appchat-c68c1.firebasestorage.app',
  );
 
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbONCK87n7UfBA28h9O488_tWTDrZzbXc',
    appId: '1:53591657125:android:f8b7aacd7255e0d4312d36',
    messagingSenderId: '53591657125',
    projectId: 'appchat-c68c1',
    storageBucket: 'appchat-c68c1.firebasestorage.app',
  );
 
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1Nk-nVoBBbdj1BdSljusKcMBIxNzs8Rs',
    appId: '1:53591657125:ios:617006fb12e302f8312d36',
    messagingSenderId: '53591657125',
    projectId: 'appchat-c68c1',
    storageBucket: 'appchat-c68c1.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );
 
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1Nk-nVoBBbdj1BdSljusKcMBIxNzs8Rs',
    appId: '1:53591657125:ios:617006fb12e302f8312d36',
    messagingSenderId: '53591657125',
    projectId: 'appchat-c68c1',
    storageBucket: 'appchat-c68c1.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );
 
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRt1EfgkH2jT39BdtdXRpYcRU5Xr-9-Hg',
    appId: '1:53591657125:web:7b73e69647d8dc6f312d36',
    messagingSenderId: '53591657125',
    projectId: 'appchat-c68c1',
    authDomain: 'appchat-c68c1.firebaseapp.com',
    storageBucket: 'appchat-c68c1.firebasestorage.app',
  );
}